[[https://melpa.org/#/openhab-mode][https://melpa.org/packages/openhab-mode-badge.svg]]

* openhab-modes

This is a collection of major modes for working with various [[https://openhab.org][openHAB]] files.

The primary objective is to get syntax highlighting and indentation working (both as-you-write and
formatting of the entire buffer) and while *far* from complete, it's absolutely usable for editing
rules files as well as viewing the others.

Modes:
- [[openhab-mode]]
- [[openhab-item-mode]]
- [[openhab-persistence-mode]]
- [[openhab-rule-mode]]
- [[openhab-sitemap-mode]]
- [[openhab-thing-mode]]

** Why is the editing experience so poor?

Because I don't actually *edit* any of these files as they are all generated - I only view them.

That being said, if someone would like to add better support for editing (indentation comes to
mind), then please do open a PR!

** openhab-mode

Base mode from which the others inherit.

** openhab-item-mode

Support for =.items= files.

** openhab-persistence-mode

Support for =.persistence= files.

** openhab-rule-mode

=rules= files are based on [[https://www.eclipse.org/xtend/][Xtend]], so they are technically a real programming languages. I don't myself write rules using the openHAB DSL as openHAB now supports jruby rules.

** openhab-sitemap-mode

Support for =.sitemap= files.

** openhab-thing-mode

Support for =.things= files.
